const suffixList = [
		// ["ach", "ich", "ig", "icht", "igt", "at", "et", "it", "es", "is"],
		["ate", "te", "nit", "net"],
		["ede", "da", "te", "ta"],
		["ich"],
		["in"],
		["ing", "ingen", "ung", "ungen", "ens"],
		["itz", "itsch", "witz", "schütz", "ütz"],
		["ow"],
		["ach", "a", "aa", "ah"],
		["ar", "ahr"],
		["au", "aue", "oog", "ooge", "ohe", "oie"],
		["bach", "bach", "bek", "beken", "beck", "bke"],
		["berg", "bergen", "barg", "bargen"],
		// ["beuern", "beuren", "beuron", "birn"],
		["born", "bronn"],
		["bruch", "broich", "brook", "brock", "brauk"],
		["bruck", "brück", "brügge"],
		["bühl", "bühel", "bihl", "beuel", "bichel", "pichl"],
		// ["büll"],
		["burg", "borg"],
		["büttel"],
		// ["by"],
		// ["donk"],
		// ["donn"],
		["dorf", "torf", "troff", "druf", "dorp", "dörp", "torp", "trop", "trup", "torf", "torp", "trup"],
		// ["eck", "egg"],
		["feld", "felde"],
		// ["fels", ],
		// ["fleth"],
		["furt", "furt", "furth", "fürth", "ford", "fort", "vörde"],
		// ["gast"],
		// ["gmund", "gmünd"],
		["graben"],
		// ["groden", "grode"],
		// ["hafen", "haven"],
		["hag", "hagen",  "haag", "hain", "han", "hahn"],
		// ["hall"],
		// ["hardt", "hard", "haard", "haardt", "hart", "harth"],
		["hau"],
		["hausen", "haus", "husen"],
		["heim", "heimen",  "ham", "am", "hem", "em", "um"],
		["hof", "hofen", "höfen", "hoven"],
		// ["holm"],
		// ["holt"],
		["horn", "hörn"],
		["horst", "host", "ost", "hurst"],
		["hoven"],
		// ["hude"],
		["inghausen", "iehausen", "kausen", "ingheim", "igheim", "ingem", "inghoven", "ikofen", "ikon", "iken", "ingerode"],
		// ["kapell", "kapellen", "kappeln"],
		// ["kietz"],
		["kirch", "kirchen", "kark", "kerk", "kerken"],
		["leben", "legen", "lehen"],
		["leiten", "leithen"],
		// ["ley"],
		["loh", "lah", "loch", "loy"],
		["mar"],
		// ["mund", "münde", "müde", "müden", "muid", "muide"],
		// ["münster"],
		["rod", "roda", "rodt", "rode", "raht", "rath", "rade", "reut", "reuth", "reute", "ried", "ruit", "ray"],
		// ["rotte"],
		// ["ruhe"],
		["scheid"],
		// ["schlag"],
		// ["schwand", "schwende", "swende"],
		["siefen", "seifen"],
		["siel"],
		// ["stade"],
		["stadt", "stadt", "statt", "stätt", "stetten",  "städt", "stedt", "stede", "steden"],
		["stein"],
		// ["stift"],
		// ["sund"],
		["tal", "thal"],
		["torf"],
		["um"],
		["up"],
		// ["walchen"],
		["wald", "walde"],
		// ["warden"],
		["weg"],
		// ["weide"],
		["weiler", "weier", "weiher", "wil", "wyl", "wyhl", "viller"],
		["werder", "werth"],
		// ["wik", "wig"],
		["winkel"],
		// ["wiß"],
		["zell"]
	];

export default suffixList;
